apiVersion: v1
kind: Service
metadata:
  name: fast-mimilm-lb
spec:
  selector:
    app: fast-mimilm
  ports:
    - protocol: TCP
      port: 80  # Expose on port 80 externally
      targetPort: 8002  # Forward traffic to port 8002 on Pods
  type: LoadBalancer